CREATE TABLE [dbo].[customers]
(
  [Id] INT NOT NULL PRIMARY KEY,
  [FirstName] NVARCHAR(100) NOT NULL,
  [LastName] NVARCHAR(100) NOT NULL,
  [Email] NVARCHAR(255) NOT NULL,
  [CreatedDate] DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
)
